"""One-shot generator for the 4 refactored notebooks under `notebooks/`.

Run from the repo root: `python scripts/build_notebooks.py`.

Each notebook follows the same skeleton: Config -> Data -> Model -> Train (if
RUN_TRAINING) -> Evaluate clean+corrupt -> Persist outputs. Code lives in
`src/dememte/`; the notebooks orchestrate it.
"""

from __future__ import annotations

from pathlib import Path

import nbformat as nbf

ROOT = Path(__file__).resolve().parents[1]
NB_ROOT = ROOT / "notebooks"


def md(*lines: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell("\n".join(lines))


def code(*lines: str) -> nbf.NotebookNode:
    return nbf.v4.new_code_cell("\n".join(lines))


def write_nb(rel_path: str, cells: list) -> None:
    nb = nbf.v4.new_notebook()
    nb.cells = cells
    nb.metadata = {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }
    path = NB_ROOT / rel_path
    path.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(nb, path)
    print(f"wrote {path.relative_to(ROOT)}")


PREAMBLE = [
    "import sys, os",
    "from pathlib import Path",
    "ROOT = Path.cwd()",
    "while ROOT != ROOT.parent and not (ROOT / 'src' / 'dememte').exists():",
    "    ROOT = ROOT.parent",
    "if str(ROOT / 'src') not in sys.path:",
    "    sys.path.insert(0, str(ROOT / 'src'))",
    "print('repo root:', ROOT)",
]


# ============================================================================
# Notebook 01 — Baseline (ResNet18 frozen, 3-stage methodology)
# ============================================================================

def notebook_01() -> list:
    return [
        md(
            "# 01 — Baseline ResNet18 (frozen backbone)",
            "",
            "ResNet18 con backbone congelado entrenado con la **misma metodología en fases** y la **misma",
            "suite de corrupciones** que el modelo DeMemte E5. Sirve como referencia _fair 1:1_:",
            "mismo split de datos, mismas corrupciones, presupuesto de épocas equivalente.",
            "",
            "**Tres fases**:",
            "1. _warmup_ del clasificador en datos limpios (3 ep)",
            "2. _corrupt_ — train con corrupciones aleatorias p=0.7 (6 ep)",
            "3. _joint_ — refinamiento con lr reducido (10 ep)",
            "",
            "Activa `RUN_TRAINING = True` para entrenar desde cero (1× con GPU). Si está en `False` (default),",
            "carga el checkpoint guardado en `out/baseline_best.pt` y solo recomputa la evaluación.",
        ),
        code(*PREAMBLE),
        code(
            "import json",
            "from dataclasses import asdict",
            "",
            "import numpy as np",
            "import pandas as pd",
            "import torch",
            "import matplotlib.pyplot as plt",
            "",
            "from dememte.config import BaselineConfig, resolve_data_dir",
            "from dememte.data import build_loaders, seed_everything",
            "from dememte.models import ResNetBaseline",
            "from dememte.training import train_baseline_phased",
            "from dememte.evaluation import evaluate_baseline_suite, signal_curve_rows_baseline",
            "from dememte.io import save_checkpoint, load_checkpoint, write_json, write_csv, ensure_dir",
            "",
            "RUN_TRAINING = False  # flip to True to train from scratch",
            "",
            "cfg = BaselineConfig(freeze_backbone=True)",
            "cfg.data_dir = resolve_data_dir(cfg)",
            "device = 'cuda' if torch.cuda.is_available() else 'cpu'",
            "OUT = ensure_dir(ROOT / 'notebooks' / '01_baseline' / 'out')",
            "CKPT = OUT / 'baseline_best.pt'",
            "seed_everything(cfg.seed)",
            "print(json.dumps(asdict(cfg), indent=2))",
        ),
        md("## Datos"),
        code(
            "tr_loader, va_loader, te_loader, meta = build_loaders(",
            "    data_dir=cfg.data_dir,",
            "    batch_size=cfg.batch_size,",
            "    num_workers=cfg.num_workers,",
            "    val_ratio=cfg.val_ratio,",
            "    split_seed=cfg.split_seed,",
            "    protocol=cfg.benchmark_protocol,",
            ")",
            "print(meta)",
        ),
        md("## Modelo"),
        code(
            "model = ResNetBaseline(num_classes=cfg.num_classes, freeze_backbone=True).to(device)",
            "n_trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)",
            "n_total = sum(p.numel() for p in model.parameters())",
            "print(f'trainable params: {n_trainable:,} / {n_total:,}')",
        ),
        md(
            "## Entrenamiento (opcional)",
            "",
            "Si `RUN_TRAINING=False`, salta esta celda y carga el checkpoint en la siguiente.",
        ),
        code(
            "if RUN_TRAINING:",
            "    model, best_val = train_baseline_phased(model, tr_loader, va_loader, cfg, device)",
            "    save_checkpoint(model, CKPT, extra={'best_val': best_val, 'config': asdict(cfg)})",
            "    print(f'saved {CKPT} (best_val={best_val:.4f})')",
            "else:",
            "    if CKPT.exists():",
            "        payload = load_checkpoint(model, CKPT, device=device, strict=True)",
            "        print('loaded:', CKPT, '| best_val:', payload.get('best_val'))",
            "    else:",
            "        print('WARNING: no checkpoint at', CKPT, '— flip RUN_TRAINING to True to train.')",
        ),
        md("## Evaluación clean + corrupt (suite 4×3)"),
        code(
            "metrics = evaluate_baseline_suite(model, te_loader, device=device, return_predictions=True)",
            "clean_record = metrics.pop('clean_record')",
            "corrupt_records = metrics.pop('corruption_records')",
            "",
            "predictions = clean_record.pop('predictions', [])",
            "for rows in corrupt_records.values():",
            "    for rec in rows:",
            "        predictions.extend(rec.pop('predictions', []))",
            "",
            "summary = {k: v for k, v in metrics.items() if isinstance(v, (int, float))}",
            "summary.update({'protocol': meta['protocol'], 'split_seed': meta['split_seed']})",
            "write_json(summary, OUT / 'metrics.json')",
            "write_csv(predictions, OUT / 'predictions.csv')",
            "write_csv(signal_curve_rows_baseline('ResNet18-frozen-baseline', clean_record, corrupt_records), OUT / 'corrupt_curves.csv')",
            "print(json.dumps(summary, indent=2))",
        ),
        md("## Curva de robustez por severidad"),
        code(
            "curves = pd.read_csv(OUT / 'corrupt_curves.csv')",
            "fig, ax = plt.subplots(figsize=(8, 5))",
            "for corr, sub in curves[curves['corruption'] != 'clean'].groupby('corruption'):",
            "    ax.plot(sub['severity'], sub['acc'], marker='o', label=corr)",
            "clean_acc = curves[curves['corruption'] == 'clean']['acc'].iloc[0]",
            "ax.axhline(clean_acc, linestyle='--', color='k', alpha=0.5, label=f'clean ({clean_acc:.3f})')",
            "ax.set_xlabel('Severity')",
            "ax.set_ylabel('Accuracy')",
            "ax.set_title('Baseline ResNet18 (frozen) — robustness curves')",
            "ax.grid(alpha=0.3); ax.legend()",
            "ensure_dir(OUT / 'plots')",
            "fig.savefig(OUT / 'plots' / 'robustness_curves.png', dpi=120, bbox_inches='tight')",
            "plt.show()",
        ),
    ]


# ============================================================================
# Notebook 02 — E5 Winner
# ============================================================================

def notebook_02() -> list:
    return [
        md(
            "# 02 — DeMemte E5 (variante ganadora)",
            "",
            "Reproducción end-to-end de la variante ganadora `e5_combined_dropout_ood_tau_150`:",
            "backbone ResNet18 congelado + memoria VQ + atractor residual + gate adaptativo de 4 señales",
            "(uncertainty, familiarity, conflict, ood_risk).",
            "",
            "**Tres fases**:",
            "- F1: pretrain del latente con masking (35% feature dropout)",
            "- F2: atractor + gate + clasificadores con corrupciones aleatorias",
            "- F3: fine-tune conjunto limpio+corrupto + anti-pareidolia loss",
            "",
            "Con `RUN_TRAINING=False` (default) se carga el checkpoint en `out/e5_best.pt`.",
            "El checkpoint preexistente de `experiments/atracctor/out/artifacts/dememte_e5_critical/seed_42/`",
            "es compatible — la primera ejecución lo copia a `out/` si no encuentra uno local.",
        ),
        code(*PREAMBLE),
        code(
            "import json, shutil",
            "from dataclasses import asdict",
            "",
            "import numpy as np",
            "import pandas as pd",
            "import torch",
            "import matplotlib.pyplot as plt",
            "",
            "from dememte.config import E5Config, resolve_data_dir",
            "from dememte.data import build_loaders, seed_everything",
            "from dememte.models import make_dememte_e5",
            "from dememte.training import train_dememte_full",
            "from dememte.evaluation import evaluate_dememte_suite, signal_curve_rows",
            "from dememte.io import save_checkpoint, load_checkpoint, write_json, write_csv, ensure_dir",
            "",
            "RUN_TRAINING = False",
            "",
            "cfg = E5Config()",
            "cfg.data_dir = resolve_data_dir(cfg)",
            "device = 'cuda' if torch.cuda.is_available() else 'cpu'",
            "OUT = ensure_dir(ROOT / 'notebooks' / '02_e5_winner' / 'out')",
            "CKPT = OUT / 'e5_best.pt'",
            "LEGACY_CKPT = ROOT / 'experiments/atracctor/out/artifacts/dememte_e5_critical/seed_42/e5_combined_dropout_ood_tau_150/e5_combined_dropout_ood_tau_150_best.pt'",
            "seed_everything(cfg.seed)",
            "print(json.dumps(asdict(cfg), indent=2))",
        ),
        md("## Datos"),
        code(
            "tr_loader, va_loader, te_loader, meta = build_loaders(",
            "    data_dir=cfg.data_dir,",
            "    batch_size=cfg.batch_size,",
            "    num_workers=cfg.num_workers,",
            "    val_ratio=cfg.val_ratio,",
            "    split_seed=cfg.split_seed,",
            "    protocol=cfg.benchmark_protocol,",
            ")",
            "print(meta)",
        ),
        md("## Modelo E5"),
        code(
            "model = make_dememte_e5(cfg, device=device)",
            "n_trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)",
            "n_total = sum(p.numel() for p in model.parameters())",
            "print(f'params total: {n_total:,} | trainable (post-init): {n_trainable:,}')",
        ),
        md("## Entrenamiento (opcional) o carga del checkpoint"),
        code(
            "if RUN_TRAINING:",
            "    model, best_acc = train_dememte_full(model, tr_loader, va_loader, cfg, device)",
            "    save_checkpoint(model, CKPT, extra={'best_val': best_acc, 'config': asdict(cfg)})",
            "    print(f'saved {CKPT} (best_val={best_acc:.4f})')",
            "else:",
            "    if not CKPT.exists() and LEGACY_CKPT.exists():",
            "        print('seeding out/ with legacy E5 checkpoint:', LEGACY_CKPT)",
            "        shutil.copy(LEGACY_CKPT, CKPT)",
            "    payload = load_checkpoint(model, CKPT, device=device, strict=True)",
            "    print('loaded:', CKPT, '| best_val:', payload.get('best_val'))",
        ),
        md("## Evaluación clean + corrupt + métricas del gate"),
        code(
            "metrics = evaluate_dememte_suite(model, te_loader, device=device, return_predictions=True)",
            "clean_record = metrics.pop('clean_record')",
            "corrupt_records = metrics.pop('corruption_records')",
            "",
            "predictions = clean_record.pop('predictions', [])",
            "for rows in corrupt_records.values():",
            "    for rec in rows:",
            "        predictions.extend(rec.pop('predictions', []))",
            "",
            "summary = {k: v for k, v in metrics.items() if isinstance(v, (int, float, bool))}",
            "summary.update({'protocol': meta['protocol'], 'split_seed': meta['split_seed'], 'variant': 'e5_combined_dropout_ood_tau_150'})",
            "write_json(summary, OUT / 'metrics.json')",
            "write_csv(predictions, OUT / 'predictions.csv')",
            "write_csv(signal_curve_rows('e5_combined_dropout_ood_tau_150', 'E5 winner', clean_record, corrupt_records), OUT / 'signal_curves.csv')",
            "print(json.dumps(summary, indent=2))",
        ),
        md("## Curvas del gate por corrupción/severidad"),
        code(
            "curves = pd.read_csv(OUT / 'signal_curves.csv')",
            "fig, axes = plt.subplots(1, 2, figsize=(14, 5))",
            "for corr, sub in curves[curves['corruption'] != 'clean'].groupby('corruption'):",
            "    axes[0].plot(sub['severity'], sub['gate_mean'], marker='o', label=corr)",
            "    axes[1].plot(sub['severity'], sub['acc'], marker='o', label=corr)",
            "clean_row = curves[curves['corruption'] == 'clean'].iloc[0]",
            "axes[0].axhline(clean_row['gate_mean'], linestyle='--', color='k', alpha=0.5, label='clean')",
            "axes[1].axhline(clean_row['acc'], linestyle='--', color='k', alpha=0.5, label=f\"clean ({clean_row['acc']:.3f})\")",
            "axes[0].set_xlabel('Severity'); axes[0].set_ylabel('Gate mean'); axes[0].set_title('E5 gate response')",
            "axes[1].set_xlabel('Severity'); axes[1].set_ylabel('Accuracy'); axes[1].set_title('E5 robustness')",
            "for ax in axes: ax.grid(alpha=0.3); ax.legend()",
            "ensure_dir(OUT / 'gate_plots')",
            "fig.savefig(OUT / 'gate_plots' / 'gate_and_robustness.png', dpi=120, bbox_inches='tight')",
            "plt.show()",
        ),
    ]


# ============================================================================
# Notebook 03 — Ablations (8 variantes del set crítico)
# ============================================================================

def notebook_03() -> list:
    return [
        md(
            "# 03 — Ablaciones (8 variantes del set crítico)",
            "",
            "Cada variante responde una amenaza metodológica del diseño E5 — qué pasa si quitas OOD,",
            "familiarity, anti-pareidolia, si congelas VQ en Fase 3, si descongelas parcialmente el",
            "backbone, si desactivas el atractor o si comparas contra un transfer-learning puro de ResNet18.",
            "",
            "Las 8 variantes se entrenan con la misma metodología (3 fases) y se evalúan en clean + corrupt",
            "(suite 4×3). Resultados consolidados en `out/ablation_summary.csv` / `.md`.",
            "",
            "`RUN_TRAINING=True` entrena cada variante secuencialmente (~ horas en una GPU). `RUN_TRAINING=False`",
            "carga checkpoints existentes desde `out/<variant>/best.pt`; si faltan, intenta sembrarlos desde",
            "`experiments/atracctor/out/artifacts/dememte_e5_critical/seed_42/<variant>/`.",
        ),
        code(*PREAMBLE),
        code(
            "import json, shutil",
            "from dataclasses import asdict",
            "",
            "import numpy as np",
            "import pandas as pd",
            "import torch",
            "import matplotlib.pyplot as plt",
            "",
            "from dememte.config import ABLATION_SPECS, ablation_config, BaselineConfig, resolve_data_dir",
            "from dememte.data import build_loaders, seed_everything",
            "from dememte.models import make_dememte_variant, ResNetBaseline",
            "from dememte.training import train_dememte_full, train_baseline_phased",
            "from dememte.evaluation import (",
            "    evaluate_dememte_suite, evaluate_baseline_suite,",
            "    signal_curve_rows, signal_curve_rows_baseline,",
            ")",
            "from dememte.io import save_checkpoint, load_checkpoint, write_json, write_csv, ensure_dir",
            "",
            "RUN_TRAINING = False",
            "",
            "device = 'cuda' if torch.cuda.is_available() else 'cpu'",
            "OUT = ensure_dir(ROOT / 'notebooks' / '03_ablations' / 'out')",
            "LEGACY_DIR = ROOT / 'experiments/atracctor/out/artifacts/dememte_e5_critical/seed_42'",
            "",
            "data_dir = resolve_data_dir(BaselineConfig())",
            "seed_everything(42)",
        ),
        md("## Datos (compartidos entre todas las variantes)"),
        code(
            "tr_loader, va_loader, te_loader, meta = build_loaders(",
            "    data_dir=data_dir,",
            "    batch_size=16,",
            "    num_workers=2,",
            "    val_ratio=0.2,",
            "    split_seed=42,",
            "    protocol='historical_trainval_resplit',",
            ")",
            "print(meta)",
        ),
        md("## Variantes del set crítico"),
        code(
            "VARIANTS = list(ABLATION_SPECS.keys())",
            "for name in VARIANTS:",
            "    print(f'  - {name:42s}  ::  {ABLATION_SPECS[name][\"label\"]}')",
        ),
        md("## Loop de entrenamiento / carga + evaluación"),
        code(
            "all_summaries = []",
            "all_curves = []",
            "",
            "for variant in VARIANTS:",
            "    print(f'\\n=== {variant} ===')",
            "    vdir = ensure_dir(OUT / variant)",
            "    ckpt_path = vdir / 'best.pt'",
            "",
            "    if variant == 'resnet18_transfer_baseline':",
            "        cfg = BaselineConfig(freeze_backbone=True)",
            "        cfg.data_dir = data_dir",
            "        model = ResNetBaseline(num_classes=cfg.num_classes, freeze_backbone=True).to(device)",
            "        if RUN_TRAINING:",
            "            model, best_val = train_baseline_phased(model, tr_loader, va_loader, cfg, device)",
            "            save_checkpoint(model, ckpt_path, extra={'best_val': best_val, 'variant': variant})",
            "        else:",
            "            legacy = LEGACY_DIR / variant",
            "            legacy_pt = next(iter(legacy.glob('*best.pt')), None) if legacy.exists() else None",
            "            if not ckpt_path.exists() and legacy_pt is not None:",
            "                print('seeding from legacy:', legacy_pt)",
            "                shutil.copy(legacy_pt, ckpt_path)",
            "            if ckpt_path.exists():",
            "                load_checkpoint(model, ckpt_path, device=device, strict=False)",
            "            else:",
            "                print('no checkpoint; skip variant'); continue",
            "        metrics = evaluate_baseline_suite(model, te_loader, device=device)",
            "        clean_record = metrics.pop('clean_record'); corrupt_records = metrics.pop('corruption_records')",
            "        curve_rows = signal_curve_rows_baseline(variant, clean_record, corrupt_records)",
            "    else:",
            "        cfg = ablation_config(variant)",
            "        cfg.data_dir = data_dir",
            "        seed_everything(cfg.seed)",
            "        model = make_dememte_variant(cfg, device=device)",
            "        if RUN_TRAINING:",
            "            model, best_val = train_dememte_full(model, tr_loader, va_loader, cfg, device)",
            "            save_checkpoint(model, ckpt_path, extra={'best_val': best_val, 'variant': variant, 'config': asdict(cfg)})",
            "        else:",
            "            legacy = LEGACY_DIR / variant",
            "            legacy_pt = next(iter(legacy.glob('*best.pt')), None) if legacy.exists() else None",
            "            if not ckpt_path.exists() and legacy_pt is not None:",
            "                print('seeding from legacy:', legacy_pt)",
            "                shutil.copy(legacy_pt, ckpt_path)",
            "            if ckpt_path.exists():",
            "                load_checkpoint(model, ckpt_path, device=device, strict=False)",
            "            else:",
            "                print('no checkpoint; skip variant'); continue",
            "        metrics = evaluate_dememte_suite(model, te_loader, device=device)",
            "        clean_record = metrics.pop('clean_record'); corrupt_records = metrics.pop('corruption_records')",
            "        curve_rows = signal_curve_rows(variant, ABLATION_SPECS[variant]['label'], clean_record, corrupt_records)",
            "",
            "    summary = {k: v for k, v in metrics.items() if isinstance(v, (int, float, bool))}",
            "    summary.update({'variant': variant, 'label': ABLATION_SPECS[variant]['label']})",
            "    write_json(summary, vdir / 'metrics.json')",
            "    all_summaries.append(summary)",
            "    all_curves.extend(curve_rows)",
            "    print(f\"clean_acc={summary.get('clean_acc'):.4f} corrupt_acc={summary.get('corrupt_acc_avg'):.4f}\")",
            "",
            "summary_df = pd.DataFrame(all_summaries)",
            "summary_df.to_csv(OUT / 'ablation_summary.csv', index=False)",
            "write_csv(all_curves, OUT / 'ablation_curves.csv')",
            "summary_df",
        ),
        md("## Tabla comparativa (clean vs corrupt)"),
        code(
            "cols = ['variant', 'clean_acc', 'corrupt_acc_avg', 'corrupt_acc_gaussian_noise', 'corrupt_acc_pixel_mask', 'corrupt_acc_cutout', 'corrupt_acc_blur']",
            "cols = [c for c in cols if c in summary_df.columns]",
            "ranked = summary_df[cols].sort_values('corrupt_acc_avg', ascending=False)",
            "ranked.to_markdown(OUT / 'ablation_summary.md', index=False) if hasattr(ranked, 'to_markdown') else ranked.to_csv(OUT / 'ablation_summary.md', sep='|', index=False)",
            "ranked",
        ),
        md("## Comparativa visual clean vs corrupt"),
        code(
            "fig, ax = plt.subplots(figsize=(11, 5))",
            "x = np.arange(len(ranked))",
            "width = 0.35",
            "ax.bar(x - width/2, ranked['clean_acc'], width, label='clean')",
            "ax.bar(x + width/2, ranked['corrupt_acc_avg'], width, label='corrupt avg')",
            "ax.set_xticks(x); ax.set_xticklabels(ranked['variant'], rotation=35, ha='right')",
            "ax.set_ylabel('Accuracy'); ax.set_title('Ablations — clean vs corrupt (suite 4×3)')",
            "ax.grid(alpha=0.3, axis='y'); ax.legend()",
            "ensure_dir(OUT / 'plots')",
            "fig.savefig(OUT / 'plots' / 'ablations_clean_vs_corrupt.png', dpi=120, bbox_inches='tight')",
            "plt.tight_layout(); plt.show()",
        ),
    ]


# ============================================================================
# Notebook 04 — Fine-tune vs Frozen (storytelling: rompiendo el trade-off)
# ============================================================================

def notebook_04() -> list:
    return [
        md(
            "# 04 — Fine-tune con corrupciones vs DeMemte (backbone congelado)",
            "",
            "**Tesis**: el approach estándar para ganar robustez es _aumentar el dataset con corrupciones_",
            "y fine-tunear todo el modelo. Eso entrega un trade-off conocido: sube la accuracy en corrupt,",
            "baja en clean. DeMemte propone otra ruta — congelar el backbone y delegar la corrección a un",
            "gate de memoria que decide _cuándo_ intervenir. Esa diferencia debería romper el trade-off.",
            "",
            "**Condición A** — `ResNet18 fine-tune completo` con corrupciones agresivas en entrenamiento.",
            "**Condición B** — `DeMemte E5 frozen` (carga checkpoint del notebook 02).",
            "",
            "`RUN_TRAINING=True` entrena la condición A desde cero (1× GPU). B no se reentrena nunca: solo",
            "se carga el checkpoint de `notebooks/02_e5_winner/out/e5_best.pt`.",
        ),
        code(*PREAMBLE),
        code(
            "import json, shutil",
            "from dataclasses import asdict",
            "",
            "import numpy as np",
            "import pandas as pd",
            "import torch",
            "import matplotlib.pyplot as plt",
            "",
            "from dememte.config import BaselineConfig, E5Config, resolve_data_dir",
            "from dememte.data import build_loaders, seed_everything",
            "from dememte.models import ResNetBaseline, make_dememte_e5",
            "from dememte.training import train_baseline_phased",
            "from dememte.evaluation import (",
            "    evaluate_baseline_suite, evaluate_dememte_suite,",
            "    signal_curve_rows, signal_curve_rows_baseline,",
            ")",
            "from dememte.io import save_checkpoint, load_checkpoint, write_json, write_csv, ensure_dir",
            "",
            "RUN_TRAINING = False",
            "",
            "device = 'cuda' if torch.cuda.is_available() else 'cpu'",
            "OUT = ensure_dir(ROOT / 'notebooks' / '04_finetune_vs_frozen' / 'out')",
            "FT_CKPT = OUT / 'resnet_ft_best.pt'",
            "E5_CKPT = ROOT / 'notebooks' / '02_e5_winner' / 'out' / 'e5_best.pt'",
            "LEGACY_E5 = ROOT / 'experiments/atracctor/out/artifacts/dememte_e5_critical/seed_42/e5_combined_dropout_ood_tau_150/e5_combined_dropout_ood_tau_150_best.pt'",
            "seed_everything(42)",
        ),
        md("## Datos"),
        code(
            "data_dir = resolve_data_dir(BaselineConfig())",
            "tr_loader, va_loader, te_loader, meta = build_loaders(",
            "    data_dir=data_dir,",
            "    batch_size=16,",
            "    num_workers=2,",
            "    val_ratio=0.2,",
            "    split_seed=42,",
            "    protocol='historical_trainval_resplit',",
            ")",
            "print(meta)",
        ),
        md("## Condición A — ResNet18 fine-tune completo con corrupciones agresivas"),
        code(
            "ft_cfg = BaselineConfig(freeze_backbone=False)",
            "ft_cfg.data_dir = data_dir",
            "ft_cfg.train_corrupt_prob = 0.85  # aug agresivo para empujar robustez",
            "ft_cfg.backbone_lr = 1e-4",
            "ft_cfg.epochs_warmup = 2",
            "ft_cfg.epochs_corrupt = 8",
            "ft_cfg.epochs_joint = 12",
            "print(json.dumps(asdict(ft_cfg), indent=2))",
            "",
            "ft_model = ResNetBaseline(num_classes=ft_cfg.num_classes, freeze_backbone=False).to(device)",
            "if RUN_TRAINING:",
            "    ft_model, ft_best = train_baseline_phased(ft_model, tr_loader, va_loader, ft_cfg, device)",
            "    save_checkpoint(ft_model, FT_CKPT, extra={'best_val': ft_best, 'config': asdict(ft_cfg)})",
            "elif FT_CKPT.exists():",
            "    payload = load_checkpoint(ft_model, FT_CKPT, device=device, strict=True)",
            "    print('loaded FT:', FT_CKPT, '| best_val:', payload.get('best_val'))",
            "else:",
            "    print('WARNING: no FT checkpoint — flip RUN_TRAINING=True to train.')",
        ),
        md("## Condición B — DeMemte E5 frozen (carga, no reentrena)"),
        code(
            "e5_cfg = E5Config()",
            "e5_cfg.data_dir = data_dir",
            "e5_model = make_dememte_e5(e5_cfg, device=device)",
            "src = E5_CKPT if E5_CKPT.exists() else LEGACY_E5",
            "if not src.exists():",
            "    raise FileNotFoundError(f'no E5 checkpoint found at {E5_CKPT} or {LEGACY_E5}')",
            "payload = load_checkpoint(e5_model, src, device=device, strict=True)",
            "print('loaded E5:', src, '| best_val:', payload.get('best_val'))",
        ),
        md("## Evaluación paralela"),
        code(
            "ft_metrics = evaluate_baseline_suite(ft_model, te_loader, device=device)",
            "ft_clean = ft_metrics.pop('clean_record'); ft_corr = ft_metrics.pop('corruption_records')",
            "ft_summary = {k: v for k, v in ft_metrics.items() if isinstance(v, (int, float))}",
            "ft_summary['condition'] = 'A_resnet_ft_corrupt'",
            "",
            "e5_metrics = evaluate_dememte_suite(e5_model, te_loader, device=device)",
            "e5_clean = e5_metrics.pop('clean_record'); e5_corr = e5_metrics.pop('corruption_records')",
            "e5_summary = {k: v for k, v in e5_metrics.items() if isinstance(v, (int, float, bool))}",
            "e5_summary['condition'] = 'B_dememte_e5_frozen'",
            "",
            "comparison = pd.DataFrame([ft_summary, e5_summary])",
            "ft_trainable = sum(p.numel() for p in ft_model.parameters() if p.requires_grad)",
            "e5_trainable = sum(p.numel() for p in e5_model.parameters() if p.requires_grad)",
            "ft_total = sum(p.numel() for p in ft_model.parameters())",
            "e5_total = sum(p.numel() for p in e5_model.parameters())",
            "comparison['trainable_params'] = [ft_trainable, e5_trainable]",
            "comparison['total_params'] = [ft_total, e5_total]",
            "comparison['gap_clean_minus_corrupt'] = comparison['clean_acc'] - comparison['corrupt_acc_avg']",
            "comparison.to_csv(OUT / 'comparison_table.csv', index=False)",
            "comparison",
        ),
        md("## Curvas por corrupción"),
        code(
            "ft_curves = signal_curve_rows_baseline('A_resnet_ft_corrupt', ft_clean, ft_corr)",
            "e5_curves = signal_curve_rows('B_dememte_e5_frozen', 'DeMemte E5', e5_clean, e5_corr)",
            "all_curves = pd.DataFrame(ft_curves + e5_curves)",
            "all_curves.to_csv(OUT / 'comparison_curves.csv', index=False)",
            "",
            "fig, axes = plt.subplots(2, 2, figsize=(13, 9), sharey=True)",
            "for ax, corr in zip(axes.flat, ['gaussian_noise', 'pixel_mask', 'cutout', 'blur']):",
            "    for variant, sub in all_curves[all_curves['corruption'] == corr].groupby('variant'):",
            "        ax.plot(sub['severity'], sub['acc'], marker='o', label=variant)",
            "    ax.set_title(corr); ax.grid(alpha=0.3); ax.set_xlabel('Severity'); ax.set_ylabel('Accuracy'); ax.legend()",
            "ensure_dir(OUT / 'plots')",
            "fig.savefig(OUT / 'plots' / 'robustness_curves.png', dpi=120, bbox_inches='tight')",
            "plt.tight_layout(); plt.show()",
        ),
        md("## Scatter clean vs corrupt — ¿se rompe el trade-off?"),
        code(
            "fig, ax = plt.subplots(figsize=(7, 6))",
            "for _, row in comparison.iterrows():",
            "    ax.scatter(row['clean_acc'], row['corrupt_acc_avg'], s=180, label=row['condition'])",
            "    ax.annotate(row['condition'], (row['clean_acc'], row['corrupt_acc_avg']),",
            "                xytext=(8, 8), textcoords='offset points', fontsize=10)",
            "ax.plot([0, 1], [0, 1], linestyle=':', color='gray', alpha=0.5, label='clean = corrupt')",
            "ax.set_xlabel('Clean accuracy'); ax.set_ylabel('Corrupt accuracy (avg)')",
            "ax.set_title('Trade-off clean ↔ corrupt')",
            "ax.set_xlim(0.5, 1.0); ax.set_ylim(0.3, 0.8)",
            "ax.grid(alpha=0.3); ax.legend(loc='lower right')",
            "fig.savefig(OUT / 'plots' / 'scatter_tradeoff.png', dpi=120, bbox_inches='tight')",
            "plt.show()",
        ),
        md(
            "## Narrativa final",
            "",
            "Lee la columna `gap_clean_minus_corrupt` de la tabla. Si el approach del gate de memoria",
            "está cumpliendo su tesis, esperarías:",
            "",
            "- Condición A (FT con corrupciones): clean cae respecto al baseline limpio y corrupt sube — el",
            "  trade-off clásico. Gap moderado.",
            "- Condición B (DeMemte E5 frozen): clean se mantiene alta **y** corrupt mejora. Gap menor o",
            "  similar pero con ambos valores más altos.",
            "",
            "El scatter visualiza esto: si B está arriba-y-a-la-derecha de A, no estamos en la misma frontera",
            "de Pareto — el gate genuinamente rompe el trade-off.",
        ),
    ]


def main() -> None:
    write_nb("01_baseline/baseline.ipynb", notebook_01())
    write_nb("02_e5_winner/e5_winner.ipynb", notebook_02())
    write_nb("03_ablations/ablations.ipynb", notebook_03())
    write_nb("04_finetune_vs_frozen/finetune_vs_frozen.ipynb", notebook_04())


if __name__ == "__main__":
    main()
